### PR TITLE
Add progress bar

### PR DESCRIPTION
**Pull request by Outcue**
Simple progress bar.
Value is set between 0 and 1.0
Initialize with 1.0 for bar to be indeterminate.
I'll add animated example as part of the big control demo I am planning.

### CODE REVIEW

**Comment by gbracha** [comment]
Have you looked at the way the testing UI does this?

**Comment by Outcue** [comment]
I'll look!

**Comment by Outcue** [comment]
I see this in TestingProgressPresenter:

```
definition = (
	schedule: [startTests].

	errorCountHolder:: holder: [nothing].
	failureCountHolder:: holder: [nothing].
	(* progressBar:: progress. *)
	currentSelector:: label: 'no tests yet'.	
	^column: {
		(* progressBar. *)
		row: {label: 'Running '. currentSelector . label: '...'}.
		errorCountHolder.
		failureCountHolder.
	}
)
```
Progress bar is commented out. Is there another place to look?

**Comment by gbracha** [comment]
I guess I forgot that it was commented out in the web version. But it might be good case to try out the new widget.

**Comment by Outcue** [comment]
Cool. I was hoping there wasn't another version of the progress widget. I'll wire it up in the test code.

**Pull request merged**
